version: '3.9'
services:
  db:
    image: cockroachdb/cockroach:v23.1.2
    command: start-single-node --insecure
    environment:
      - COCKROACH_USER=john
      - COCKROACH_DATABASE=spoolcloud
      - TZ=Asia/Seoul
    healthcheck:
      test:
        [
          "CMD",
          "curl",
          "-f",
          "http://localhost:8080/health?ready=1"
        ]
      interval: 5s
      timeout: 10s
      retries: 5
  spoolcloud:
    image: donkie/spoolcloud:test
    environment:
      - SPOOLCLOUD_DB_TYPE=cockroachdb
      - SPOOLCLOUD_DB_HOST=db
      - SPOOLCLOUD_DB_PORT=26257
      - SPOOLCLOUD_DB_NAME=spoolcloud
      - SPOOLCLOUD_DB_USERNAME=john
      - SPOOLCLOUD_LOGGING_LEVEL=INFO
      - TZ=Europe/Stockholm
    depends_on:
      db:
        condition: service_healthy
  tester:
    image: donkie/spoolcloud-tester:latest
    volumes:
      - ./tests:/tester/tests
    environment:
      - DB_TYPE=cockroachdb
    depends_on:
      - spoolcloud
