version: '3.8'
services:
  spoolcloud:
    image: donkie/spoolcloud:test
    environment:
      - SPOOLCLOUD_LOGGING_LEVEL=INFO
      - TZ=Europe/Stockholm
  tester:
    image: donkie/spoolcloud-tester:latest
    volumes:
      - ./tests:/tester/tests
    environment:
      - DB_TYPE=sqlite
    depends_on:
      - spoolcloud
