version: '3.9'
services:
  db:
    image: mariadb:latest
    environment:
      - MARIADB_USER=john
      - MARIADB_RANDOM_ROOT_PASSWORD=yes
      - MARIADB_PASSWORD=abc
      - MARIADB_DATABASE=spoolcloud
      - MARIADB_MYSQL_LOCALHOST_USER=true
      - TZ=Asia/Seoul
    healthcheck:
      test:
        [
          "CMD",
          "/usr/local/bin/healthcheck.sh",
          "--su-mysql",
          "--connect",
          "--innodb_initialized"
        ]
      interval: 1s
      timeout: 5s
      retries: 30
  spoolcloud:
    image: donkie/spoolcloud:test
    environment:
      - SPOOLCLOUD_DB_TYPE=mysql
      - SPOOLCLOUD_DB_HOST=db
      - SPOOLCLOUD_DB_PORT=3306
      - SPOOLCLOUD_DB_NAME=spoolcloud
      - SPOOLCLOUD_DB_USERNAME=john
      - SPOOLCLOUD_DB_PASSWORD=abc
      - SPOOLCLOUD_LOGGING_LEVEL=INFO
      - TZ=Europe/Stockholm
    depends_on:
      db:
        condition: service_healthy
  tester:
    image: donkie/spoolcloud-tester:latest
    volumes:
      - ./tests:/tester/tests
    environment:
      - DB_TYPE=mysql
    depends_on:
      - spoolcloud
