version: '3.8'
services:
  db:
    image: postgres:11-alpine
    environment:
      - POSTGRES_PASSWORD=abc
      - TZ='GMT+4'
      - PGTZ='GMT+4'
  spoolcloud:
    image: donkie/spoolcloud:test
    environment:
      - SPOOLCLOUD_DB_TYPE=postgres
      - SPOOLCLOUD_DB_HOST=db
      - SPOOLCLOUD_DB_PORT=5432
      - SPOOLCLOUD_DB_NAME=postgres
      - SPOOLCLOUD_DB_USERNAME=postgres
      - SPOOLCLOUD_DB_PASSWORD=abc
      - SPOOLCLOUD_LOGGING_LEVEL=INFO
      - TZ=Europe/Stockholm
    depends_on:
      - db
  tester:
    image: donkie/spoolcloud-tester:latest
    volumes:
      - ./tests:/tester/tests
    environment:
      - DB_TYPE=postgres
    depends_on:
      - spoolcloud
