"""add_auth_and_notification_tables.

Revision ID: 786ac154edbd
Revises: 415a8f855e14
Create Date: 2025-11-26 10:25:58.898098
"""

import sqlalchemy as sa
from alembic import op
from datetime import datetime

# revision identifiers, used by Alembic.
revision = '786ac154edbd'
down_revision = '415a8f855e14'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_id'), 'user', ['id'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    
    op.create_table('api_key',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('key_prefix', sa.String(length=16), nullable=False),
    sa.Column('key_hash', sa.String(length=256), nullable=False),
    sa.Column('label', sa.String(length=64), nullable=False),
    sa.Column('last_used_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_key_id'), 'api_key', ['id'], unique=False)
    op.create_index(op.f('ix_api_key_key_hash'), 'api_key', ['key_hash'], unique=False)
    op.create_index(op.f('ix_api_key_user_id'), 'api_key', ['user_id'], unique=False)
    
    op.create_table('filament_preset',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_filament_preset_id'), 'filament_preset', ['id'], unique=False)
    op.create_index(op.f('ix_filament_preset_user_id'), 'filament_preset', ['user_id'], unique=False)
    
    op.create_table('internal_notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=128), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.String(length=16), nullable=False),
    sa.Column('data', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_internal_notification_id'), 'internal_notification', ['id'], unique=False)
    op.create_index(op.f('ix_internal_notification_user_id'), 'internal_notification', ['user_id'], unique=False)
    
    op.create_table('notification_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('webhook_url', sa.String(length=512), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_config_id'), 'notification_config', ['id'], unique=False)
    op.create_index(op.f('ix_notification_config_user_id'), 'notification_config', ['user_id'], unique=True)

    with op.batch_alter_table('filament', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('preset_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_filament_preset_id_fk'), ['preset_id'], unique=False)
        batch_op.create_index(op.f('ix_filament_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_filament_user_id_user', 'user', ['user_id'], ['id'])
        batch_op.create_foreign_key('fk_filament_preset_id_filament_preset', 'filament_preset', ['preset_id'], ['id'])

    with op.batch_alter_table('spool', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_spool_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_spool_user_id_user', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(op.f('ix_vendor_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_vendor_user_id_user', 'user', ['user_id'], ['id'])

    # ### Data Migration ###
    user_table = sa.table('user',
        sa.Column('id', sa.Integer, primary_key=True),
        sa.Column('username', sa.String),
        sa.Column('password_hash', sa.String),
        sa.Column('role', sa.String),
        sa.Column('created_at', sa.DateTime)
    )

    op.bulk_insert(user_table, [
        {
            'username': 'admin',
            'password_hash': '$argon2id$v=19$m=65536,t=3,p=4$0Vor5Vyr1fp/T4lRqhXiPA$52BjRKaNCwZctE1UVWR3UvwqrXRYh8B+udTo50zzjKQ',
            'role': 'admin',
            'created_at': datetime.utcnow()
        }
    ])

    # Assign existing data to admin
    op.execute("UPDATE vendor SET user_id = (SELECT id FROM user WHERE username = 'admin') WHERE user_id IS NULL")
    op.execute("UPDATE filament SET user_id = (SELECT id FROM user WHERE username = 'admin') WHERE user_id IS NULL")
    op.execute("UPDATE spool SET user_id = (SELECT id FROM user WHERE username = 'admin') WHERE user_id IS NULL")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vendor_user_id_user', type_='foreignkey')
        batch_op.drop_index(op.f('ix_vendor_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('spool', schema=None) as batch_op:
        batch_op.drop_constraint('fk_spool_user_id_user', type_='foreignkey')
        batch_op.drop_index(op.f('ix_spool_user_id'))
        batch_op.drop_column('user_id')

    with op.batch_alter_table('filament', schema=None) as batch_op:
        batch_op.drop_constraint('fk_filament_user_id_user', type_='foreignkey')
        batch_op.drop_constraint('fk_filament_preset_id_filament_preset', type_='foreignkey')
        batch_op.drop_index(op.f('ix_filament_user_id'))
        batch_op.drop_index(op.f('ix_filament_preset_id_fk'))
        batch_op.drop_column('preset_id')
        batch_op.drop_column('user_id')

    op.drop_index(op.f('ix_notification_config_user_id'), table_name='notification_config')
    op.drop_index(op.f('ix_notification_config_id'), table_name='notification_config')
    op.drop_table('notification_config')
    op.drop_index(op.f('ix_internal_notification_user_id'), table_name='internal_notification')
    op.drop_index(op.f('ix_internal_notification_id'), table_name='internal_notification')
    op.drop_table('internal_notification')
    op.drop_index(op.f('ix_filament_preset_user_id'), table_name='filament_preset')
    op.drop_index(op.f('ix_filament_preset_id'), table_name='filament_preset')
    op.drop_table('filament_preset')
    op.drop_index(op.f('ix_api_key_user_id'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_key_hash'), table_name='api_key')
    op.drop_index(op.f('ix_api_key_id'), table_name='api_key')
    op.drop_table('api_key')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_id'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
