"""add_notification_types.

Revision ID: fe50b58e05d2
Revises: 8c2262511833
Create Date: 2025-11-29 12:32:38.908105
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fe50b58e05d2'
down_revision = '8c2262511833'
branch_labels = None
"""add_notification_types.

Revision ID: fe50b58e05d2
Revises: 8c2262511833
Create Date: 2025-11-29 12:32:38.908105
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = 'fe50b58e05d2'
down_revision = '8c2262511833'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_config', sa.Column('notification_types', sa.JSON(), nullable=True, comment='List of enabled notification types'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_config', 'notification_types')
    # ### end Alembic commands ###
