"""add_language_to_notification_config.

Revision ID: 629a2e51360c
Revises: fe50b58e05d2
Create Date: 2025-11-29 14:48:19.254194
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '629a2e51360c'
down_revision = 'fe50b58e05d2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notification_config', sa.Column('language', sa.String(length=10), nullable=False, server_default='zh-CN', comment='Notification language (zh-CN, en-US)'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notification_config', 'language')
    # ### end Alembic commands ###
