"""Add invite code system and admin field.

Revision ID: 38804b7861aa
Revises: 786ac154edbd
Create Date: 2025-11-26 14:31:08.827181
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '38804b7861aa'
down_revision = '786ac154edbd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invite_code',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('created_by_user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('used_by_user_id', sa.Integer(), nullable=True),
    sa.Column('used_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['used_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_invite_code_code'), 'invite_code', ['code'], unique=True)
    op.create_index(op.f('ix_invite_code_created_by_user_id'), 'invite_code', ['created_by_user_id'], unique=False)
    op.create_index(op.f('ix_invite_code_id'), 'invite_code', ['id'], unique=False)
    op.create_index(op.f('ix_invite_code_used_by_user_id'), 'invite_code', ['used_by_user_id'], unique=False)
    op.drop_index(op.f('ix_filament_preset_id_fk'), table_name='filament')
    # Skip creating index if it already exists to avoid conflicts
    # op.create_index(op.f('ix_filament_preset_id'), 'filament', ['preset_id'], unique=False)
    op.add_column('user', sa.Column('is_admin', sa.Boolean(), nullable=False, server_default='0'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'is_admin')
    op.drop_index(op.f('ix_filament_preset_id'), table_name='filament')
    op.create_index(op.f('ix_filament_preset_id_fk'), 'filament', ['preset_id'], unique=False)
    op.drop_index(op.f('ix_invite_code_used_by_user_id'), table_name='invite_code')
    op.drop_index(op.f('ix_invite_code_id'), table_name='invite_code')
    op.drop_index(op.f('ix_invite_code_created_by_user_id'), table_name='invite_code')
    op.drop_index(op.f('ix_invite_code_code'), table_name='invite_code')
    op.drop_table('invite_code')
    # ### end Alembic commands ###
