"""add_code_to_filament_preset.

Revision ID: 37293a96c8a9
Revises: 19c5d72b372a
Create Date: 2025-11-27 14:36:43.798015
"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = '37293a96c8a9'
down_revision = '19c5d72b372a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Perform the upgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_index(op.f('ix_filament_preset_id'), 'filament', ['preset_id'], unique=False)
    # op.add_column('filament_preset', sa.Column('code', sa.String(length=32), nullable=True))
    with op.batch_alter_table('notification_config', schema=None) as batch_op:
        batch_op.alter_column('id',
                   existing_type=sa.INTEGER(),
                   nullable=False,
                   autoincrement=True)
        batch_op.alter_column('channel',
                   existing_type=sa.VARCHAR(length=32),
                   nullable=False)
        batch_op.alter_column('is_enabled',
                   existing_type=sa.BOOLEAN(),
                   nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Perform the downgrade."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notification_config', 'is_enabled',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('notification_config', 'channel',
               existing_type=sa.VARCHAR(length=32),
               nullable=True)
    op.alter_column('notification_config', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('filament_preset', 'code')
    op.drop_index(op.f('ix_filament_preset_id'), table_name='filament')
    # ### end Alembic commands ###
